#!/bin/bash

# This script generates 3 start packages, from which a workshop can be ran. It'll royally screw
# up the current directory's contents, so only run this on a clean repository that's safely pushed
# somewhere.

git reset HEAD --hard
rm -rf target/ */target project/project/target example-3-reaktive/journal */.classpath */.settings */.project */bin
rm *.tgz

rm -rf example-3-reaktive/src/main/java
cp -rp example-2-persistence/src/main/java example-3-reaktive/src/main
rm -rf example-2-persistence/*
rm -rf example-1-akka/*
rm -rf example-0-base/*
tar czvf workshop-3-reaktive.tgz build.sbt example* project README* sbt*

git reset HEAD --hard
rm -rf example-2-reaktive/src/main/java
cp -rp example-1-akka/src/main/java example-2-persistence/src/main
rm -rf example-3-reaktive/*
rm -rf example-1-akka/*
rm -rf example-0-base/*
tar czvf workshop-2-persistence.tgz build.sbt example* project README* sbt*

git reset HEAD --hard
rm -rf example-1-akka/src/main/java
cp -rp example-0-base/src/main/java example-1-akka/src/main
rm -rf example-3-reaktive/*
rm -rf example-2-persistence/*
rm -rf example-0-base/*
tar czvf workshop-1-akka.tgz build.sbt example* project README* sbt*

git reset HEAD --hard

